### ISSUE TITLE
can't see the canditates menu for snippet

### ISSUE THREAD

**Issue by lookforit** [kspearrin/Visual-Studio-jQuery-Code-Snippets#16]
Hi
I have to type the **exactly entire** abbreviation word, and then press `Tab`, the snippet is inserted.
Any way to see the  menu for the candidate snippets, just as demo picture in `Visual Studio extension gallery `page ?

I have `Resharper` and `VsVim`  installed.

Thanks.

**Comment by lookforit** [comment]
After some testing ,It's proved that which is the business of `Reshaper ` 's intelliSense behavior : `Reshaper ` ignores the snippet defined by `VS `.

Nothing relatas to this extension.

Thank you.

**Comment by kspearrin** [comment]
Yes, Resharper changes the way code snippets work unfortunately causing these kinds of issues. Let me know if you figure out a workaround. This is one of the reasons I stopped using Resharper.

**Comment by rulrok** [comment]
I use ReSharper as well and can't get this extension to work. If you find a solution please provide us with it. If I find I'll post it here.
