### ISSUE TITLE
double $

### ISSUE THREAD

**Issue by sonicshadow** [kspearrin/Visual-Studio-jQuery-Code-Snippets#20]
ver:1.6.0
for example：
jqClick and Tab
output :
$$(selector).click(function (e) {
        e.preventDefault();
});

**Comment by kspearrin** [comment]
I am not able to reproduce this.

**Comment by sonicshadow** [comment]
source code
<Code Language="javascript"><![CDATA[$$.ajax({
    type: "$method$",
    url: "$url$",
    data: "$data$",
    dataType: "$dataType$",
    success: function (response) {
        $end$
    }
});]]></Code>

after delete one $ ,my vs2015 update2 not display double
<Code Language="javascript"><![CDATA[$.ajax({
    type: "$method$",
    url: "$url$",
    data: "$data$",
    dataType: "$dataType$",
    success: function (response) {
        $end$
    }
});]]></Code>

**Comment by kspearrin** [comment]
The double `$$` is to escape the `$` for jQuery. All jQuery snippets are done this way. I am not sure why this is an issue for you, but noone else has reported this problem. I am using VS 2015 Update 2 as well.

Did you install the the snippets through the extension manager?

**Comment by sonicshadow** [comment]
I think is vs2015 problem, today I update vs2015 update 2 release ,this bug is fixed
