### ISSUE TITLE
Doesn't appear to be working for .js files in Visual Studio 2017?

### ISSUE THREAD

**Issue by ryanbuening** [kspearrin/Visual-Studio-jQuery-Code-Snippets#25]
I installed extension 1.7.0 in Visual Studio 2017 Community.

If I open a .cshtml file I do get a list of available snippets by typing **<jq**.

However, if I open a .js file and type **jq** I do not get a list of available snippets.

Am I doing something wrong?

**Comment by ryanbuening** [comment]
Disregard. I need to use $jq. Working great. Thanks.

**Comment by ryanbuening** [comment]
This is working with Visual Studio 2017 Community on my Windows 10 machine, but not on my Windows 7 machine. Would the different Windows versions cause a conflict?

**Comment by sergip76** [comment]
It doesn't work for me on Visual Studio 2017 Community. I type jq and when I choose the JQuery function from the list I only see the Snippet word.

**Comment by kspearrin** [comment]
@sergip76 @ryanbuening 

I don't know if things changed in VS 2017 or what but to invoke the snippet you have to hit the tab key when selecting it from the intellisense dropdown.

I seem to remember being able to press enter in VS 2015 and it would do the same but in 2017 that just prints the snippet word like you mentioned. I would be wrong though but I don't have 2015 installed anymore to verify.

**Comment by sergip76** [comment]
If I hit the tab key it doesn't work. Same result.

**Comment by kspearrin** [comment]
Weird. It's working fine for me, though I am using 2017 Enterprise.

**Comment by sergip76** [comment]
I've just noticed that it works fine if I push the TAB key longer than 1 second, not just clicking.
Thanks.
